repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.62.2
    hooks:
      - id: golangci-lint
        files: ^(cmd|core)/.*

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types: [javascript, jsx, ts, tsx, css, html, markdown, yaml]

  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go-mod-tidy
        entry: powershell -Command "go mod tidy"
        language: system
        files: go.mod|go.sum
        pass_filenames: false
      - id: vscode-lint
        name: VS Code Extension Lint
        entry: powershell.exe -Command "cd extensions/vscode; npm run lint"
        language: system
        files: ^extensions/vscode/.*
        pass_filenames: false
