package db

// GenerateDummyEmbedding creates a deterministic hash-based embedding for testing.
// In production, embeddings are generated by the LLM provider (Gemini, Claude, etc.)
// This allows tests to run without requiring API keys while maintaining correct vector semantics.
func GenerateDummyEmbedding(text string, dimensions int) []float32 {
	vec := make([]float32, dimensions)
	hash := fnvHash(text)
	for i := 0; i < dimensions; i++ {
		val := float32(((hash>>uint(i%32))&0xFFFF))/32768.0 - 1.0
		vec[i] = val
	}
	// Normalize to unit vector
	norm := float32(0)
	for _, v := range vec {
		norm += v * v
	}
	norm = float32(sqrt(float64(norm)))
	if norm > 0 {
		for i := range vec {
			vec[i] /= norm
		}
	}
	return vec
}

func fnvHash(s string) uint64 {
	var h uint64 = 14695981039346656037
	for i := 0; i < len(s); i++ {
		h ^= uint64(s[i])
		h *= 1099511628211
	}
	return h
}

func sqrt(x float64) float64 {
	if x <= 0 {
		return 0
	}
	z := x
	for i := 0; i < 10; i++ {
		z = (z + x/z) / 2
	}
	return z
}
