package db

import (
	"context"
	"fmt"
	"runtime"

	"github.com/philippgille/chromem-go"
)

// MemoryService manages the indexing of volatile and permanent knowledge.
// Embeddings must be pre-generated by the LLM provider (Gemini, Claude, etc.)
// and passed via the Embedding parameter. ChromemStore does NOT call remote APIs.
type MemoryService struct {
	db         *chromem.DB
	collection *chromem.Collection
}

func NewMemoryService(ctx context.Context, dbPath string) (*MemoryService, error) {
	db, err := chromem.NewPersistentDB(dbPath, false)
	if err != nil {
		return nil, fmt.Errorf("memory_db_init_failed: %w", err)
	}
	col, err := db.GetOrCreateCollection("knowledge_base", nil, nil)
	if err != nil {
		return nil, err
	}

	return &MemoryService{
		db:         db,
		collection: col,
	}, nil
}

// StoreInsight guarda um fato no banco vetorial.
// embedding must be pre-generated by the LLM provider.
func (s *MemoryService) StoreInsight(ctx context.Context, id, content string, metadata map[string]string, embedding []float32) error {
	doc := chromem.Document{
		ID:        id,
		Content:   content,
		Metadata:  metadata,
		Embedding: embedding,
	}
	return s.collection.AddDocument(ctx, doc)
}

// StoreInsightWithFallback stores with a dummy embedding if none provided.
// Use this for testing. In production, always generate embeddings via the LLM provider.
func (s *MemoryService) StoreInsightWithFallback(ctx context.Context, id, content string, metadata map[string]string) error {
	vec := GenerateDummyEmbedding(content, 768)
	return s.StoreInsight(ctx, id, content, metadata, vec)
}

// SearchInsight performs local RAG over accumulated knowledge.
// queryVec must be pre-generated by the LLM provider.
func (s *MemoryService) SearchInsight(ctx context.Context, query string, queryVec []float32, topK int) ([]string, error) {
	if len(queryVec) == 0 {
		queryVec = GenerateDummyEmbedding(query, 768)
	}

	results, err := s.collection.QueryEmbedding(ctx, queryVec, topK, nil, nil)
	if err != nil {
		return nil, err
	}

	var insights []string
	for _, res := range results {
		insights = append(insights, res.Content)
	}
	return insights, nil
}

// BatchStore stores multiple insights at once.
// Embeddings must be pre-generated by the LLM provider.
func (s *MemoryService) BatchStore(ctx context.Context, items []struct {
	ID, Content string
	Metadata    map[string]string
	Embedding   []float32
}) error {
	docs := make([]chromem.Document, 0, len(items))
	for _, item := range items {
		vec := item.Embedding
		if len(vec) == 0 {
			vec = GenerateDummyEmbedding(item.Content, 768)
		}
		docs = append(docs, chromem.Document{
			ID:        item.ID,
			Content:   item.Content,
			Metadata:  item.Metadata,
			Embedding: vec,
		})
	}
	return s.collection.AddDocuments(ctx, docs, runtime.NumCPU())
}
