package db

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"time"

	vecos "github.com/Kaffyn/Vectora/core/os"
	"github.com/philippgille/chromem-go"
)

// SchemaVersion is the current version of the vector DB schema.
// Increment this when making breaking changes to the schema.
const SchemaVersion = 1

// ChromemStore wraps chromem-go with persistent storage.
// Embeddings must be pre-generated by the LLM provider (Gemini, Claude, etc.)
// and passed in Chunk.Vector. ChromemStore only stores and retrieves — it does NOT
// call remote APIs for embedding. This keeps the vector DB as a pure storage layer.
type ChromemStore struct {
	db     *chromem.DB
	dbPath string
}

// NewVectorStore initializes folder-based persistence for embeddings using chromem-go.
func NewVectorStore() (*ChromemStore, error) {
	osMgr, err := vecos.NewManager()
	if err != nil {
		return nil, err
	}
	baseDir, _ := osMgr.GetAppDataDir()
	path := filepath.Join(baseDir, "data", "chroma")
	return NewVectorStoreAtPath(path)
}

func NewVectorStoreAtPath(path string) (*ChromemStore, error) {
	if err := os.MkdirAll(path, 0755); err != nil {
		return nil, err
	}

	db, err := chromem.NewPersistentDB(path, false)
	if err != nil {
		return nil, fmt.Errorf("vectora_internal_err: silent failure in chromem persistent db binding: %w", err)
	}

	return &ChromemStore{db: db, dbPath: path}, nil
}

// UpsertChunk adds or updates a chunk in the vector store.
// Chunk.Vector MUST contain the pre-generated embedding from the LLM provider.
// ChromemStore does NOT generate embeddings — it only stores pre-computed vectors.
func (s *ChromemStore) UpsertChunk(ctx context.Context, collection string, chunk Chunk) error {
	return s.UpsertChunks(ctx, collection, []Chunk{chunk})
}

// UpsertChunks adds or updates multiple chunks in the vector store in batch.
// This is significantly faster for initial project indexing.
func (s *ChromemStore) UpsertChunks(ctx context.Context, collection string, chunks []Chunk) error {
	if len(chunks) == 0 {
		return nil
	}

	c, err := s.db.GetOrCreateCollection(collection, nil, nil)
	if err != nil {
		return err
	}

	docs := make([]chromem.Document, 0, len(chunks))
	for _, chunk := range chunks {
		if len(chunk.Vector) == 0 {
			continue // Skip segments without embeddings
		}
		docs = append(docs, chromem.Document{
			ID:        chunk.ID,
			Content:   chunk.Content,
			Metadata:  chunk.Metadata,
			Embedding: chunk.Vector,
		})
	}

	if len(docs) == 0 {
		return nil
	}

	return c.AddDocuments(ctx, docs, runtime.NumCPU())
}

// Query performs a vector similarity search using a pre-computed query embedding.
// queryVector must be generated by the same LLM provider used for indexing.
func (s *ChromemStore) Query(ctx context.Context, collection string, queryVector []float32, topK int) ([]ScoredChunk, error) {
	if len(queryVector) == 0 {
		return nil, fmt.Errorf("queryVector is empty — query embedding must be generated by the LLM provider")
	}

	c, err := s.db.GetOrCreateCollection(collection, nil, nil)
	if err != nil {
		return nil, err
	}

	res, err := c.QueryEmbedding(ctx, queryVector, topK, nil, nil)
	if err != nil {
		return nil, err
	}

	var results []ScoredChunk
	for _, doc := range res {
		results = append(results, ScoredChunk{
			Chunk: Chunk{
				ID:       doc.ID,
				Content:  doc.Content,
				Metadata: doc.Metadata,
				Vector:   doc.Embedding,
			},
			Score: doc.Similarity,
		})
	}

	return results, nil
}

func (s *ChromemStore) DeleteCollection(ctx context.Context, collection string) error {
	return s.db.DeleteCollection(collection)
}

func (s *ChromemStore) CollectionExists(ctx context.Context, collection string) bool {
	c := s.db.GetCollection(collection, nil)
	return c != nil
}

// SchemaMetadata stores versioning and metadata about the vector DB.
type SchemaMetadata struct {
	Version   int    `json:"version"`
	Timestamp string `json:"timestamp,omitempty"`
}

// CheckAndUpdateSchema verifies the vector DB schema version and returns true
// if the schema is current. If there's a mismatch, it logs a warning and returns false.
func (s *ChromemStore) CheckAndUpdateSchema(ctx context.Context) bool {
	meta, err := s.getSchemaMetadata()
	if err != nil || meta.Version == 0 {
		// First time or corrupted metadata — initialize it
		_ = s.setSchemaMetadata(SchemaMetadata{
			Version:   SchemaVersion,
			Timestamp: time.Now().UTC().Format(time.RFC3339),
		})
		return true
	}

	if meta.Version != SchemaVersion {
		// Schema mismatch — caller should re-index
		return false
	}

	return true
}

// getSchemaMetadata reads the schema version from disk.
func (s *ChromemStore) getSchemaMetadata() (*SchemaMetadata, error) {
	metaPath := filepath.Join(s.dbPath, ".schema_version.json")
	data, err := os.ReadFile(metaPath)
	if err != nil {
		return nil, err
	}

	var meta SchemaMetadata
	if err := json.Unmarshal(data, &meta); err != nil {
		return nil, err
	}

	return &meta, nil
}

// setSchemaMetadata writes the schema metadata to disk.
func (s *ChromemStore) setSchemaMetadata(meta SchemaMetadata) error {
	metaPath := filepath.Join(s.dbPath, ".schema_version.json")
	data, _ := json.MarshalIndent(meta, "", "  ")
	return os.WriteFile(metaPath, data, 0644)
}

func (s *ChromemStore) Close() error {
	// Chromem-go does not require a formal close for persistence,
	// as it flushes on cada operation in persistent mode.
	s.db = nil
	return nil
}
