package db

import (
	"context"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"sync"
	"time"

	vecos "github.com/Kaffyn/Vectora/internal/os"
	"go.etcd.io/bbolt"
)

// SchemaVersion is the current version of the vector DB schema.
// Increment this when making breaking changes to the schema.
const SchemaVersion = 1

// ChromemStore implements VectorStore interface using BoltDB.
// NOTE: This is a simplified implementation. It performs linear search instead of HNSW.
// Future optimization: integrate HNSW for faster similarity search.
// Embeddings must be pre-generated by the LLM provider (Gemini, Claude, etc.)
// and passed in Chunk.Vector. ChromemStore only stores and retrieves — it does NOT
// call remote APIs for embedding. This keeps the vector DB as a pure storage layer.
type ChromemStore struct {
	db   *bbolt.DB
	dbPath string
	mu   sync.RWMutex
}

// SchemaMetadata stores versioning and metadata about the vector DB.
type SchemaMetadata struct {
	Version   int    `json:"version"`
	Timestamp string `json:"timestamp,omitempty"`
}

// NewVectorStore initializes folder-based persistence for embeddings using BoltDB.
func NewVectorStore() (*ChromemStore, error) {
	osMgr, err := vecos.NewManager()
	if err != nil {
		return nil, err
	}
	baseDir, _ := osMgr.GetAppDataDir()
	path := filepath.Join(baseDir, "data", "vectora_embeddings.db")
	return NewVectorStoreAtPath(path)
}

// NewVectorStoreAtPath creates a new vector store at the specified path.
func NewVectorStoreAtPath(path string) (*ChromemStore, error) {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return nil, fmt.Errorf("failed to create vector store directory: %w", err)
	}

	db, err := bbolt.Open(path, 0600, &bbolt.Options{Timeout: 1 * time.Second})
	if err != nil {
		return nil, fmt.Errorf("failed to open BoltDB: %w", err)
	}

	store := &ChromemStore{
		db:     db,
		dbPath: path,
	}

	// Initialize buckets
	if err := db.Update(func(tx *bbolt.Tx) error {
		if _, err := tx.CreateBucketIfNotExists([]byte("__schema__")); err != nil {
			return err
		}
		return nil
	}); err != nil {
		db.Close()
		return nil, err
	}

	return store, nil
}

// UpsertChunk adds or updates a chunk in the vector store.
// Chunk.Vector MUST contain the pre-generated embedding from the LLM provider.
func (s *ChromemStore) UpsertChunk(ctx context.Context, collection string, chunk Chunk) error {
	return s.UpsertChunks(ctx, collection, []Chunk{chunk})
}

// UpsertChunks adds or updates multiple chunks in the vector store in batch.
// This is significantly faster for initial project indexing.
func (s *ChromemStore) UpsertChunks(ctx context.Context, collection string, chunks []Chunk) error {
	if len(chunks) == 0 {
		return nil
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	return s.db.Update(func(tx *bbolt.Tx) error {
		// Create or get the collection bucket
		collectionBucket, err := tx.CreateBucketIfNotExists([]byte("collection:" + collection))
		if err != nil {
			return fmt.Errorf("failed to create collection bucket: %w", err)
		}

		// Store each chunk
		for _, chunk := range chunks {
			if len(chunk.Vector) == 0 {
				continue // Skip chunks without embeddings
			}

			// Serialize chunk
			data, err := json.Marshal(chunk)
			if err != nil {
				return fmt.Errorf("failed to marshal chunk %s: %w", chunk.ID, err)
			}

			// Store in BoltDB
			if err := collectionBucket.Put([]byte(chunk.ID), data); err != nil {
				return fmt.Errorf("failed to store chunk %s: %w", chunk.ID, err)
			}
		}

		return nil
	})
}

// Query performs a vector similarity search using a pre-computed query embedding.
// Uses cosine distance and linear search (brute force).
// queryVector must be generated by the same LLM provider used for indexing.
func (s *ChromemStore) Query(ctx context.Context, collection string, queryVector []float32, topK int) ([]ScoredChunk, error) {
	if len(queryVector) == 0 {
		return nil, fmt.Errorf("queryVector is empty — query embedding must be generated by the LLM provider")
	}

	s.mu.RLock()
	defer s.mu.RUnlock()

	var results []ScoredChunk

	err := s.db.View(func(tx *bbolt.Tx) error {
		collectionBucket := tx.Bucket([]byte("collection:" + collection))
		if collectionBucket == nil {
			return nil // Collection doesn't exist, return empty
		}

		// Linear scan through all chunks
		err := collectionBucket.ForEach(func(k, v []byte) error {
			var chunk Chunk
			if err := json.Unmarshal(v, &chunk); err != nil {
				return nil // Skip malformed chunks
			}

			if len(chunk.Vector) == 0 {
				return nil // Skip chunks without embeddings
			}

			// Calculate similarity
			score := cosineSimilarity(queryVector, chunk.Vector)

			results = append(results, ScoredChunk{
				Chunk: chunk,
				Score: score,
			})

			return nil
		})

		return err
	})

	if err != nil {
		return nil, fmt.Errorf("query failed: %w", err)
	}

	// Sort by score descending and take top K
	topResults := topK
	if topResults > len(results) {
		topResults = len(results)
	}

	// Simple selection sort for topK (good enough for now)
	for i := 0; i < topResults && i < len(results); i++ {
		maxIdx := i
		for j := i + 1; j < len(results); j++ {
			if results[j].Score > results[maxIdx].Score {
				maxIdx = j
			}
		}
		if maxIdx != i {
			results[i], results[maxIdx] = results[maxIdx], results[i]
		}
	}

	if topResults < len(results) {
		results = results[:topResults]
	}

	return results, nil
}

// DeleteCollection removes all vectors and metadata for a collection.
func (s *ChromemStore) DeleteCollection(ctx context.Context, collection string) error {
	s.mu.Lock()
	defer s.mu.Unlock()

	return s.db.Update(func(tx *bbolt.Tx) error {
		return tx.DeleteBucket([]byte("collection:" + collection))
	})
}

// CollectionExists checks if a collection exists in the vector store.
func (s *ChromemStore) CollectionExists(ctx context.Context, collection string) bool {
	s.mu.RLock()
	defer s.mu.RUnlock()

	exists := false
	s.db.View(func(tx *bbolt.Tx) error {
		exists = tx.Bucket([]byte("collection:" + collection)) != nil
		return nil
	})

	return exists
}

// CheckAndUpdateSchema verifies the vector DB schema version and returns true
// if the schema is current. If there's a mismatch, it logs a warning and returns false.
func (s *ChromemStore) CheckAndUpdateSchema(ctx context.Context) bool {
	return s.db.Update(func(tx *bbolt.Tx) error {
		schemaBucket := tx.Bucket([]byte("__schema__"))
		if schemaBucket == nil {
			return nil
		}

		data := schemaBucket.Get([]byte("version"))
		if data != nil {
			var meta SchemaMetadata
			if err := json.Unmarshal(data, &meta); err == nil && meta.Version == SchemaVersion {
				return nil // Schema is current
			}
		}

		// Update schema metadata
		meta := SchemaMetadata{
			Version:   SchemaVersion,
			Timestamp: time.Now().UTC().Format(time.RFC3339),
		}
		data, _ = json.Marshal(meta)
		return schemaBucket.Put([]byte("version"), data)
	}) == nil
}

// Close closes the database connection.
func (s *ChromemStore) Close() error {
	s.mu.Lock()
	defer s.mu.Unlock()

	if s.db != nil {
		return s.db.Close()
	}

	return nil
}

// Private helper functions

// cosineSimilarity calculates cosine similarity between two vectors
func cosineSimilarity(a, b []float32) float32 {
	if len(a) != len(b) || len(a) == 0 {
		return 0.0
	}

	var dotProduct, normA, normB float32
	for i := range a {
		dotProduct += a[i] * b[i]
		normA += a[i] * a[i]
		normB += b[i] * b[i]
	}

	if normA == 0 || normB == 0 {
		return 0.0
	}

	return dotProduct / (float32(math.Sqrt(float64(normA))) * float32(math.Sqrt(float64(normB))))
}
